#!/usr/bin/env python
import openerp

if __name__ == "__main__":
    openerp.cli.main()
     # openerp.tools.autoreload_main(openerp.cli.main)
     
# vim:expandtab:smartindent:tabstop=4:softtabstop=4:shiftwidth=4:
