# -*- encoding: utf-8 -*-
{
    "name": "Business Intelligence",
    "version": "2.0",
    "category" : "富光",
    "description": """Business Intelligence""",
    "author": "Zero",
    "website": "www.fga.fuguang.cn",
    "depends": ["base","web_ht",'product'],
    "init_xml": [],
    "update_xml": [
                #"security/group.xml",
                #"security/ir.model.access.csv",
                #"wizard/change_name.xml",
                "bi.xml",],
    "demo_xml": [],
    "installable": True,
    "active": False,
    "application":True,
    
    "js":[
          "static/js/exporting.js",
          "static/js/highstock.js",
          "static/js/jquery.ui.min.js",
          "static/js/jquery.cookies.js",
          "static/js/jquery.pjax.js",
          "static/js/formalize.min.js",
          "static/js/jquery.metadata.js",
          "static/js/jquery.validate.js",
          "static/js/jquery.checkboxes.js",
          "static/js/jquery.chosen.js",
          "static/js/jquery.fileinput.js",
          "static/js/jquery.datatables.js",
          "static/js/jquery.sourcerer.js",
          "static/js/jquery.calendar.js",
          "static/js/jquery.inputtags.min.js",
          "static/js/wymeditor/jquery.wymeditor.js",
          "static/js/jquery.livequery.js",
          "static/js/cufon/cufon-yui.js",
          "static/js/cufon/700.font.js",
          "static/js/application.js",
          "static/js/1.js",
          ],
    "css":[]
}